spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/auction_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml # default
    enabled: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

#logging:
#  pattern:
#    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

file:
  directory: images

app:
  jwt:
    access:
      secret: AxdbTQmW/abSjS3TpqhS2rHHUTtK8ESb0xq9uueSj34=
      expiration:
        seconds: 3600
    refresh:
        secret: fv0Q2PIP4I9oUhg1rYKqK2jHv4RFMDei
        expiration:
          seconds: 36000
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001